// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXgvmXxrAKglsdx3LoeOv_aPnotxKi4G8',
    appId: '1:582394959607:web:a5c97347e5309b46a425f2',
    messagingSenderId: '582394959607',
    projectId: 'tiktok-sask-project',
    authDomain: 'tiktok-sask-project.firebaseapp.com',
    storageBucket: 'tiktok-sask-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx5JyAFxTaAFgDMeTA-KIYfs07OZVZmYE',
    appId: '1:582394959607:android:a2f11bb9f97b3ef4a425f2',
    messagingSenderId: '582394959607',
    projectId: 'tiktok-sask-project',
    storageBucket: 'tiktok-sask-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1mWJtbe35ZzIb50YIe8qUdKpTgmsalE',
    appId: '1:582394959607:ios:707e98ead7397ea0a425f2',
    messagingSenderId: '582394959607',
    projectId: 'tiktok-sask-project',
    storageBucket: 'tiktok-sask-project.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );
}
